spring:
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
  cloud.stream:
    bindings:
      onlineConsumer-in-0:
        destination: online
      bindings:
        onlineConsumer-in-0:
          consumer:
            configuration:
              value:
                deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      binder:
        brokers:
          - localhost:9092